name: ElysiumEnderChests
version: '${project.version}'
main: ru.wryuin.elysiumenderchests.ElysiumEnderChests
api-version: '1.13'
authors: [wryuin]
description: 'Плагин, добавляющий переносные эндер-сундуки для игроков'
website: 'https://github.com/nxp1ne/ElysiumEnderChests'
commands:
  enderchest:
    aliases: [ec]
    description: Основная команда плагина ElysiumEnderChests
permissions:
  elysiumec.admin:
    description: Позволяет использовать все команды администратора
    default: op
  elysiumec.use:
    description: Позволяет использовать эндер-сундук
    default: true
  elysiumec.enderchest.see.own:
    description: Позволяет открыть свой эндер-сундук через команду
    default: true
  elysiumec.enderchest.see.*:
    description: Позволяет открыть эндер-сундук любого игрока
    default: op
