item_enderchest:
  name: '&#b302fb&lЭ&#b902f9&lн&#c002f6&lд&#c602f4&lе&#cc01f1&lр&#d301ef&l-&#d901ed&lс&#df01ea&lу&#e601e8&lн&#f200e3&lд&#f900e0&lу&#ff00de&lк'
  lore:
    - ''
    - ' &7- &fЭндер-сундук который может'
    - '     &fпомочь в любое время!'
    - ''
    - ' &#3afb00● &f- Активация на ПКМ.'
    - ''
  glow: false # Свечения предмета
  should_retrieve: false # Забирать ли у игрока эндер сундук когда он уже открыл его?
  delay:
    enable: true
    time: 5 # Время в секундах
    message: '&#3afb00● &f- Вы недавно использовали эндер-сундук! Пожалуйста подождите &#3afb00{time} &fсекунд для повторного открытие эндер-сундука'
messages:
  noPermission: '&#3afb00● &f- У вас нет прав!'